SPFS/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SPFS.Models
{
    public class SupplierListViewModel
    {
        
      
        public int CID { get; set; }

        [Display(Name = "DUNS")]
        public string Duns { get; set; }

        [Display(Name = "Supplier Name")]
        public string Name { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }

        [Display(Name="Address") ]
        public string Address
        {
            get
            {
                return Address_1 + " " + Address_2 + " " + City + " " + State;
                //return string.Format("Address1 :{0}; Address2:{1}\n City: {2} / State: {3}",new string[] { this.Address_1.Trim(),this.Address_2.Trim(),this.City.Trim(),this.State.Trim() }); //Address_1 + " " + Address_2 + " " + City + " " + State; 
            }
        }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }

       
        [Display(Name = "Zip")]
        public string Postal_Code { get; set; }

        [Display(Name = "Active")]
        public bool SPFS_Active { get; set; }
    }

    public class SupplierCacheViewModel
    {        
        public int CID { get; set; }

        [Display(Name = "DUNS")]
        public string Duns { get; set; }

        public string ERPSupplierID { get; set; }

        public int Gdis_org_entity_ID { get; set; }

        public string CombinedKey
        {
            get
            {
                return ERPSupplierID + Gdis_org_entity_ID;
            }
        }


        [Display(Name = "Supplier Name")]
        public string Name { get; set; }
        
        [Display(Name = "Active")]
        public bool SPFS_Active { get; set; }

        public int SpendSupplierID { get; set; }
    }
}

SPFS/Controllers/SupplierController.cs
using PagedList;
using PagedList.Mvc;
using SPFS.DAL;
using SPFS.Helpers;
using SPFS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SPFS.Controllers
{
    public class SupplierController : BaseController
    {
        // GET: Supplier

        public ActionResult Index1()
        {
            //Clear Tempdata of Search Criteria
            InitializeSearchCriteria();
            return RedirectToAction("Index");
        }

        private void InitializeSearchCriteria()
        {
            TempData["SupplierSearchCriteria"] = new GeneralSearchCriteria { Active = 2, Page = 1, SearchText = string.Empty, CurrentSort = " " };
        }

        public ActionResult Index(int? page)
        {
            CreateViewBags();
            List<SupplierListViewModel> suppliers = new List<SupplierListViewModel>();

            if (TempData["SupplierSearchCriteria"] == null) InitializeSearchCriteria();
            GeneralSearchCriteria objSearch = (GeneralSearchCriteria)TempData["SupplierSearchCriteria"];
            suppliers = GetSuppliers(objSearch);
            suppliers = SortByInput(objSearch.CurrentSort, suppliers);

            int pageNumber = objSearch.Page.HasValue ? objSearch.Page.Value : 1;
            return View(suppliers.ToPagedList(pageNumber, SPFSConstants.SupplierPageSize));
        }

        private List<SupplierListViewModel> GetSuppliers(GeneralSearchCriteria ObjSearch)
        {
            List<SupplierListViewModel> suppliers;
            using (Repository rep = new Repository())
            {
                var supplier = (from supp in rep.Context.SPFS_SUPPLIERS
                                select new SupplierListViewModel()
                                {
                                    CID = supp.CID,
                                    Duns = supp.Duns,
                                    Name = supp.Name,
                                    Address_1 = supp.Address_1,
                                    Address_2 = supp.Address_2,
                                    City = supp.City,
                                    State = supp.State,
                                    Country = supp.Country,
                                    Postal_Code = supp.Postal_Code,
                                    SPFS_Active = supp.SPFS_Active

                                });
                if (ObjSearch.Active.HasValue)
                {
                    if (ObjSearch.Active.Value == 1) supplier = supplier.Where(item => item.SPFS_Active);
                    if (ObjSearch.Active.Value == 0) supplier = supplier.Where(item => !item.SPFS_Active);

                }
                if (!string.IsNullOrEmpty(ObjSearch.SearchText))
                {
                    supplier = supplier.Where(item => item.Name.Contains(ObjSearch.SearchText) || item.Duns.Contains(ObjSearch.SearchText) || item.CID.ToString().Contains(ObjSearch.SearchText));

                }
                suppliers = SortByInput(ObjSearch.CurrentSort, supplier.ToList());
            }

            return suppliers;
        }

        private void CreateViewBags()
        {
            List<SelectListItem> list = new List<SelectListItem>() { new SelectListItem { Value = "1", Text = "Active" }, new SelectListItem { Value = "0", Text = "Inactive" },
             new SelectListItem { Value = "2", Text = "All"} };
            ViewBag.ActiveList = list;
        }

        /// <summary>
        /// Method to Get supplier's Overview
        /// </summary>
        /// 
        /// <returns></returns>
        public ActionResult ShowDetails(int? cid)
        {
            if (!cid.HasValue || cid <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupplierListViewModel supplier = new SupplierListViewModel();
            using (Repository rep = new Repository())
            {
                supplier = (from sup in rep.Context.SPFS_SUPPLIERS
                            where sup.CID == cid
                            select new SupplierListViewModel()
                            {
                                Name = sup.Name,
                                Duns = sup.Duns,
                                CID = sup.CID,
                                Address_1 = sup.Address_1,
                                Address_2 = sup.Address_2,
                                City = sup.City,
                                Country = sup.Country,
                                Postal_Code = sup.Postal_Code,
                                State = sup.State,
                                SPFS_Active = sup.SPFS_Active ? true : false,


                            }).FirstOrDefault();
                if (supplier == null)
                {
                    return HttpNotFound();
                }
            }
            return View(supplier);
        }

        /// <summary>
        /// Method to Save Active supplier's Overview
        /// </summary>
        /// 
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShowDetails(SupplierListViewModel supplier)
        {

            using (Repository rep = new Repository())
            {
                var supplr = rep.Context.SPFS_SUPPLIERS.Where(c => c.CID == supplier.CID).FirstOrDefault();
                if (TryUpdateModel(supplr))
                {
                    supplr.SPFS_Active = supplier.SPFS_Active;
                    supplr.Modified_by = new Utilities().GetCurrentUser().UserName;
                    supplr.Modified_date = DateTime.Now;

                    rep.Context.SaveChanges();

                    return RedirectToAction("Index");


                }

            }
            return View(supplier);
        }


        /// <summary>
        /// Method to Get suppliers by sort
        /// </summary>
        /// <param name="id"></param>
        /// <param name="search"></param>
        /// <param name="sortby"></param>
        /// <returns></returns>
        public ActionResult GetSuppliersBySort(int? id, string search, string sortby)
        {
            try
            {
                int pageno = 1;
                List<SupplierListViewModel> suppliers = null;
                ViewData["ActiveId"] = id.HasValue ? id.Value : 0;

                GeneralSearchCriteria objSearch = (GeneralSearchCriteria)TempData["SupplierSearchCriteria"];
                objSearch.Active = id;
                objSearch.CurrentSort = sortby;
                objSearch.SearchText = search;
                TempData["SupplierSearchCriteria"] = objSearch;

                suppliers = GetSuppliers(objSearch);
                pageno = objSearch.Page.HasValue ? objSearch.Page.Value : 1;
                return PartialView("_SupplierList", suppliers.ToPagedList(pageno, SPFSConstants.SupplierPageSize));
            }
            catch (Exception)
            {
                Utilities util = new Utilities();
                string msg = "error occured while loading suppliers information";
                throw new Exception(util.GetDivElements(msg, "alert alert-danger", "Error ! "));

            }
           
        }
        /// <summary>
        /// Method to Sort the suppliers by input 
        /// </summary>
        /// <param name="sortby"></param>
        /// <param name="suppliers"></param>
        /// <returns></returns>
        private List<SupplierListViewModel> SortByInput(string sortby, List<SupplierListViewModel> suppliers)
        {
            ViewData["NameSort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("Name Asc") ? "Name desc" : "Name Asc";
            ViewData["CIDSort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("CID") ? "CID desc" : "CID Asc";
            ViewData["DUNSSort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("DUNS Asc") ? "DUNS desc" : "DUNS Asc";
            ViewData["CitySort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("City Asc") ? "City desc" : "City Asc";
            ViewData["CountrySort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("Country Asc") ? "Country desc" : "Country Asc";
            ViewData["IsActiveSort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("IsActive Asc") ? "IsActive desc" : "IsActive Asc";
            ViewData["ActiveSort"] = sortby;
            switch (sortby)
            {
                case "Name desc":
                    suppliers = suppliers.OrderByDescending(s => s.Name).ToList();
                    break;
                case "Name Asc":
                    suppliers = suppliers.OrderBy(s => s.Name).ToList();
                    break;
                case "CID desc":
                    suppliers = suppliers.OrderByDescending(s => s.CID).ToList();
                    break;
                case "CID Asc":
                    suppliers = suppliers.OrderBy(s => s.CID).ToList();
                    break;
                case "DUNS desc":
                    suppliers = suppliers.OrderByDescending(s => s.Duns).ToList();
                    break;
                case "DUNS Asc":
                    suppliers = suppliers.OrderBy(s => s.Duns).ToList();
                    break;
                case "City desc":
                    suppliers = suppliers.OrderByDescending(s => s.City).ToList();
                    break;
                case "City Asc":
                    suppliers = suppliers.OrderBy(s => s.City).ToList();
                    break;
                case "Country desc":
                    suppliers = suppliers.OrderByDescending(s => s.Country).ToList();
                    break;
                case "Country Asc":
                    suppliers = suppliers.OrderBy(s => s.Country).ToList();
                    break;
               
                case "IsActive desc":

SPFS/Views/Supplier/Index.cshtml
@using SPFS.Models;

@model IEnumerable<SPFS.Models.SupplierListViewModel>
@{
    ViewBag.Title = "All Suppliers";
    GeneralSearchCriteria objSearch = (GeneralSearchCriteria)TempData["SupplierSearchCriteria"];
    TempData.Keep("SupplierSearchCriteria");
}

<h2>All Suppliers</h2>
<hr />
@using (Html.BeginForm())
{

<div class="row col-md-12" style="padding-top: 5px">
    <div class="col-md-3">
        @Html.Label("Active")
        @Html.DropDownList("activeId", ViewBag.ActiveList as IEnumerable<SelectListItem>, new { @class = "form-control" })
    </div>
    <div class="col-md-9">
        <div class="form-group col-md-6">
            @Html.Label("Search by")
            <div class="input-group">
                @Html.TextBox("search", "", new { @class = "form-control", placeholder = "Search by Supplier Name, CID, DUNS..." })
                <span class="input-group-btn">
                    <button id="btnSearch" type="button" value="Search" class="btn btn-primary ">
                        <span class="glyphicon glyphicon-search"></span>
                        <span>Search</span>
                    </button>
                </span>
            </div>
        </div>
    </div>
</div>

<div class="container col-md-12">
    <div class="row pull-right">
        <a href="@Url.Action("ExportData", "Supplier", new { fileName = "Suppliers" })" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-export"></span>Export
        </a>

     
    </div>
</div>

<div id="output" class="row" style="margin-top: 5px">
    @Html.Partial("_SupplierList", Model)
</div>

<div class="container col-md-12">
    <div class="row pull-right">
        <a href="@Url.Action("ExportData", "Supplier", new { fileName = "Suppliers" })" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-export"></span>Export
        </a>
    </div>
</div>
}


<script type="text/javascript">
    $(document).ready(function () {
        $('#activeId').focus();
        $('#activeId').val('@objSearch.Active');
        $('#search').val('@objSearch.SearchText');

        function keypressHandler(e) {
            if (e.which == 13) {
                e.preventDefault(); //stops default action: submitting form
                $(this).blur();
                $('#btnSearch').focus().click();//give your submit an ID
            }
        }

        $(this).keypress(keypressHandler);

        //Will refresh the Suppliers based on Activen or InActive
        $('#activeId').change(function () {
            var activeId = $('#activeId').val();
            var search = $('#search').val();
            $.ajax({
                url: '@Url.Action("GetSupplierByActiveOrInActive", "Supplier")',
                //Passes the content of an input up
                data: { id: activeId, search: search },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                async: false,
                success: function (data) {
                    $('#output').children().remove();
                    $('#output').html(data);
                }
            });
        });

        //Will refresh the Suppliers based on selection on Search click.
        $('#btnSearch').click(function () {
            $("#dlgmodal").dialog('open');
            $('#dlgmodal span').text('Loading Suppliers...');
            var activeId = $('#activeId').val();
            var search = $('#search').val();

            $.ajax({
                url: '@Url.Action("GetSupplierBySearch", "Supplier")',
                //Passes the content of an input up
                data: { id: activeId, search: search },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                //async: false,
                success: function (data) {
                    $('#output').children().remove();
                    $('#output').append($(data));
                    $("#dlgmodal").closest('.ui-dialog-content').dialog("close");
                }
            });
        });

        //Sorting
        $(document).on("click", ".sortby", function (ev) {
            var activeId = $('#activeId').val();
            var search = $('#search').val();
            var sortby = $(this).attr('data-sortBy');
            $.ajax({
                url: '@Url.Action("GetSuppliersBySort", "Supplier")',
                //Passes the content of an input up
                data: { id: activeId, search: search, sortby: sortby },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                async: false,
                success: function (data) {
                    $('#output').children().remove();
                    $('#output').html(data);
                }
            });
        });

    });

</script>

SPFS/Views/Supplier/ShowDetails.cshtml
@model SPFS.Models.SupplierListViewModel

@{
    ViewBag.Title = "Show Details";
    var text = Model.SPFS_Active ? "Active" : "In Active";
}
@using (Html.BeginForm())
{ 
    @Html.AntiForgeryToken()
    

    <h2>Supplier Details</h2>

    <div class="container">
        <section class="well form-horizontal form-widgets col-sm-12" style="margin:10px; width:95%;">
            <h4 class="ra-well-title">
                Supplier : @Model.Name
            </h4>
            <hr />
            <div class="form-horizontal form-widgets col-sm-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.CID, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.CID</h5>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Duns, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Duns</h5>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Name</h5>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Address</h5>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.City</h5>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.State</h5>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Country</h5>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Postal_Code, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Postal_Code</h5>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.SPFS_Active, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="input-group">
                        <div class="input-group-addon">
                            @Html.CheckBoxFor(model => model.SPFS_Active, new { @class = "saccCheckbox", id = "IsActive" })
                        </div>
                        @Html.Label(text, new { @class = "label label-success", id = "ActiveText" })
                    </div>
                    @Html.ValidationMessageFor(model => model.SPFS_Active)


                </div>
            </div>
        </section>
        <div class="row col-md-12">
            <div class="row pull-right">
                <a href="@Url.Action("Index")" class="btn btn-primary btn-sm">
                    <span class="glyphicon glyphicon-circle-arrow-left"></span>Back to List
                </a>
                <button type="submit" class="btn btn-primary btn-sm" id="btnSave">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                    <span>Save</span>
                </button>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $("input#IsActive").change(function () {
            var text = $(this).is(':checked') ? "Active" : "InActive"
            $("#ActiveText").html(text);
        });



    });

</script>

SPFS/Views/Supplier/_SupplierList.cshtml
@using PagedList.Mvc;
@using PagedList;

@model IPagedList<SPFS.Models.SupplierListViewModel>
@{

}
<div class="container col-md-12">
    <table class="table table-condensed table-hover">
        <tr class="active">
            <th>
                <a href="#" data-sortby="@ViewData["NameSort"]" class="sortby">@Html.DisplayNameFor(model => model.First().Name)</a>
            </th>
            <th>
                <a href="#" data-sortby="@ViewData["CIDSort"]" class="sortby">@Html.DisplayNameFor(model => model.First().CID)</a>
            </th>
            <th>
                <a href="#" data-sortby="@ViewData["DUNSSort"]" class="sortby">@Html.DisplayNameFor(model => model.First().Duns)</a>
            </th>

            <th>
                <a href="#" data-sortby="@ViewData["CitySort"]" class="sortby">@Html.DisplayNameFor(model => model.First().City)</a>
            </th>
            <th>
                <a href="#" data-sortby="@ViewData["CountrySort"]" class="sortby">@Html.DisplayNameFor(model => model.First().Country)</a>
            </th>

           
            <th class="actalign">
                <a href="#" data-sortby="@ViewData["IsActiveSort"]" class="sortby">@Html.DisplayNameFor(model => model.First().SPFS_Active)</a>
            </th>



        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="6">
                    <div class="alert alert-warning" role="alert">
                        
                        <strong>Warning!</strong> @SPFS.Helpers.Utilities.NO_RESULT
                    </div>
                </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.Name, "ShowDetails", new { cid = item.CID })

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Duns)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Country)
                    </td>
                  
                    <td style="text-align:center">
                        @Html.DisplayFor(modelItem => item.SPFS_Active)

                    </td>


                </tr>
            }
        }
    </table>
    <div id="myPager">
        @if (Model.Count() > 0)
        {
            @Html.PagedListPager(Model, page => Url.Action("SearchByPage", new { page, search = Request.QueryString["search"], sortby = @ViewData["ActiveSort"], activeId = Convert.ToInt32(ViewData["ActiveId"]) }))
        }
    </div>
</div>