SPFS/Models/Sites.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SPFS.Models
{
    public class SiteListViewModel
    {
        public int SiteID { get; set; }

        [Display(Name = "GDIS ORG ENTITY ID")]
        public int Gdis_org_entity_ID { get; set; }

        [Display(Name = "GDIS ORG PARENT ID")]
        public Nullable<int> Gdis_org_Parent_ID { get; set; }

        [Display(Name = "Location")]
        public string Name { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }

        [Display(Name = "Country")]
        public string Country { get; set; }

        [Display(Name = "Zip")]
        public string Postal_Code { get; set; }

        
        [Display(Name = "Active")]
        public bool SPFS_Active { get; set; }

        [Display(Name = "Address")]
        public string Address
        {
            get
            {
                return Address_1 + " " + Address_2 + " " + City + " " + State;
            }
        }


    }

    public class SelectSiteGDIS
    {
        public int SiteID { get; set; }

        public int Gdis_org_entity_ID { get; set; }

        public Nullable<int> Gdis_org_Parent_ID { get; set; }

        public string Name { get; set; }
    }
}

SPFS/Controllers/SiteController.cs
using PagedList;
using SPFS.DAL;
using SPFS.Helpers;
using SPFS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SPFS.Controllers
{
    public class SiteController : BaseController
    {
        // GET: Sites
        public ActionResult Index1()
        {
            //Clear Tempdata of Search Criteria
            InitializeSearchCriteria();
            return RedirectToAction("Index");
        }

        private void InitializeSearchCriteria()
        {
            TempData["SiteSearchCriteria"] = new GeneralSearchCriteria { Active = 2, Page = 1, SearchText = string.Empty, CurrentSort = " " };
        }

        public ActionResult Index(int? page)
        {
            CreateViewBags();
            List<SiteListViewModel> Sites = new List<SiteListViewModel>();

            if (TempData["SiteSearchCriteria"] == null) InitializeSearchCriteria();
            GeneralSearchCriteria objSearch = (GeneralSearchCriteria)TempData["SiteSearchCriteria"];
            Sites = GetSites(objSearch);
            Sites = SortByInput(objSearch.CurrentSort, Sites);

            int pageNumber = objSearch.Page.HasValue ? objSearch.Page.Value : 1;
            return View(Sites.ToPagedList(pageNumber, SPFSConstants.SitePageSize));
        }

        private List<SiteListViewModel> GetSites(GeneralSearchCriteria ObjSearch)
        {
            List<SiteListViewModel> Sites;
            using (Repository rep = new Repository())
            {
               var Site= (from site in rep.Context.SPFS_SITES
                     select new SiteListViewModel()
                     {
                         SiteID =site.SiteID,
                         Gdis_org_entity_ID = site.Gdis_org_entity_ID,
                         Gdis_org_Parent_ID = site.Gdis_org_Parent_ID,
                         Name = site.Name,
                         Address_1 = site.Address_1,
                         Address_2 = site.Address_2,
                         City = site.City,
                         State = site.State,
                         Country = site.Country,
                         Postal_Code = site.Postal_Code,
                         SPFS_Active = site.SPFS_Active,


                     });
                if (ObjSearch.Active.HasValue)
                {
                    if (ObjSearch.Active.Value == 1) Site = Site.Where(item => item.SPFS_Active);
                    if (ObjSearch.Active.Value == 0) Site = Site.Where(item => !item.SPFS_Active);

                }
                if (!string.IsNullOrEmpty(ObjSearch.SearchText))
                {
                     Site = Site.Where(item => item.Name.Contains(ObjSearch.SearchText) || item.Gdis_org_entity_ID.ToString().Contains(ObjSearch.SearchText) || item.Gdis_org_Parent_ID.ToString().Contains(ObjSearch.SearchText)); 
                    
                }
                Sites = SortByInput(ObjSearch.CurrentSort, Site.ToList());
            }

            return Sites;
        }

        private void CreateViewBags()
        {
            List<SelectListItem> list = new List<SelectListItem>() { new SelectListItem { Value = "1", Text = "Active" }, new SelectListItem { Value = "0", Text = "Inactive" },
             new SelectListItem { Value = "2", Text = "All"} };
            ViewBag.ActiveList = list;
        }
        /// <summary>
        /// Method to Get Sites by sort
        /// </summary>
        /// <param name="id"></param>
        /// <param name="search"></param>
        /// <param name="sortby"></param>
        /// <returns></returns>
        public ActionResult GetSitesBySort(int? id, string search, string sortby)
        {
            try
            { 
                int pageno = 1;
                List<SiteListViewModel> Sites = null;
                ViewData["ActiveId"] = id.HasValue ? id.Value : 0;

                GeneralSearchCriteria objSearch = (GeneralSearchCriteria)TempData["SiteSearchCriteria"];
                objSearch.Active = id;
                objSearch.CurrentSort = sortby;
                objSearch.SearchText = search;
                TempData["SiteSearchCriteria"] = objSearch;

                Sites = GetSites(objSearch);
                pageno = objSearch.Page.HasValue ? objSearch.Page.Value : 1;
                return PartialView("_SiteList", Sites.ToPagedList(pageno, SPFSConstants.SitePageSize));

            }
            catch (Exception)
            {
                Utilities util = new Utilities();
                string msg = "error occured while loading sites information";
                throw new Exception(util.GetDivElements(msg, "alert alert-danger", "Error ! "));

            }
            
        }
        /// <summary>
        /// Method to Sort the Sites by input 
        /// </summary>
        /// <param name="sortby"></param>
        /// <param name="Sites"></param>
        /// <returns></returns>
        private List<SiteListViewModel> SortByInput(string sortby, List<SiteListViewModel> Sites)
        {
            ViewData["NameSort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("Name Asc") ? "Name desc" : "Name Asc";
            ViewData["GDISORGSort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("CID") ? "GDISORG desc" : "GDISORG Asc";
            ViewData["GDISPARSort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("GDISPAR Asc") ? "GDISPAR desc" : "GDISPAR Asc";
            ViewData["CountrySort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("Country Asc") ? "Country desc" : "Country Asc";
            ViewData["ZipSort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("Zip Asc") ? "Zip desc" : "Zip Asc";
            ViewData["IsActiveSort"] = String.IsNullOrEmpty(sortby) || sortby.Equals("IsActive Asc") ? "IsActive desc" : "IsActive Asc";
            ViewData["ActiveSort"] = sortby;
            switch (sortby)
            {
                case "Name desc":
                    Sites = Sites.OrderByDescending(s => s.Name).ToList();
                    break;
                case "Name Asc":
                    Sites = Sites.OrderBy(s => s.Name).ToList();
                    break;
                case "GDISORG desc":
                    Sites = Sites.OrderByDescending(s => s.Gdis_org_entity_ID).ToList();
                    break;
                case "GDISORG Asc":
                    Sites = Sites.OrderBy(s => s.Gdis_org_entity_ID).ToList();
                    break;
                case "GDISPAR desc":
                    Sites = Sites.OrderByDescending(s => s.Gdis_org_Parent_ID).ToList();
                    break;
                case "GDISPAR Asc":
                    Sites = Sites.OrderBy(s => s.Gdis_org_Parent_ID).ToList();
                    break;
                case "Country desc":
                    Sites = Sites.OrderByDescending(s => s.Country).ToList();
                    break;
                case "Country Asc":
                    Sites = Sites.OrderBy(s => s.Country).ToList();
                    break;
                case "Zip desc":
                    Sites = Sites.OrderByDescending(s => s.Postal_Code).ToList();
                    break;
                case "Zip Asc":
                    Sites = Sites.OrderBy(s => s.Postal_Code).ToList();
                    break;
                case "IsActive desc":
                    Sites = Sites.OrderByDescending(s => s.SPFS_Active).ToList();
                    break;
                case "IsActive Asc":
                    Sites = Sites.OrderBy(s => s.SPFS_Active).ToList();
                    break;
                default:
                    Sites = Sites.OrderBy(s => s.Name).ThenBy(ss => ss.Gdis_org_entity_ID).ToList();
                    break;
            }
            return Sites;

        }

        /// <summary>
        /// Method to retrieve Sites by input 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="search"></param>
        /// <param name="page"></param>
        /// <param name="sortby"></param>
        /// <returns></returns>
        public ActionResult GetSiteByActiveOrInActive(int? id, string search)
        {
            int pageno = 1;
            List<SiteListViewModel> Sites = null;

            GeneralSearchCriteria objSearch = (GeneralSearchCriteria)TempData["SiteSearchCriteria"];
            objSearch.Active = id;
            objSearch.SearchText = search;
            Sites = GetSites(objSearch);
            pageno = objSearch.Page.Value;
            TempData["SiteSearchCriteria"] = objSearch;
            return PartialView("_SiteList", Sites.ToPagedList(pageno, SPFSConstants.SitePageSize));
        }
        /// <summary>
        /// Method to retrieve Sites by input 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="search"></param>
        /// <param name="page"></param>
        /// <param name="sortby"></param>
        /// <returns></returns>
        public ActionResult GetSiteBySearch(int? id, string search)
        {
            int pageno = 1;
            List<SiteListViewModel> Sites = null;

            GeneralSearchCriteria objSearch = (GeneralSearchCriteria)TempData["SiteSearchCriteria"];
            objSearch.Active = id;
            objSearch.SearchText = search;
            Sites = GetSites(objSearch);
            //pageno = objSearch.Page.Value;
            TempData["SiteSearchCriteria"] = objSearch;
            return PartialView("_SiteList", Sites.ToPagedList(pageno, SPFSConstants.SitePageSize));
        }
        /// <summary>
        /// Method to retrieve Sites by page
        /// </summary>
        /// <param name="search"></param>
        /// <param name="page"></param>
        /// <param name="sortby"></param>
        /// <param name="activeId"></param>
        /// <returns></returns>
        public ActionResult SearchByPage(int? page)
        {
            CreateViewBags();

SPFS/Views/Site/Index.cshtml
@using SPFS.Models;

@model IEnumerable<SPFS.Models.SiteListViewModel>

@{
    ViewBag.Title = "All Sites";
    GeneralSearchCriteria objSearch = (GeneralSearchCriteria)TempData["SiteSearchCriteria"];
    TempData.Keep("SiteSearchCriteria");
}

<h2>All Sites</h2>
<hr />
@using (Html.BeginForm())
{

    <div class="row col-md-12" style="padding-top: 5px">
        <div class="col-md-3">
            @Html.Label("Active")
            @Html.DropDownList("activeId", ViewBag.ActiveList as IEnumerable<SelectListItem>, new { @class = "form-control" })
        </div>
        <div class="col-md-9">
            <div class="form-group col-md-6">
                @Html.Label("Search by")
                <div class="input-group">
                    @Html.TextBox("search", "", new { @class = "form-control", placeholder = "Search by Location Name, GDIS ORG ENTITY..." })
                    <span class="input-group-btn">
                        <button id="btnSearch" type="button" value="Search" class="btn btn-primary">
                            <span class="glyphicon glyphicon-search"></span>
                            <span>Search</span>
                        </button>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div class="container col-md-12">
        <div class="row pull-right">
            <a href="@Url.Action("ExportData", "Site", new { fileName = "Sites" })" class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-export"></span>Export
            </a>


        </div>
    </div>

    <div id="output" class="row" style="margin-top: 5px">
        @Html.Partial("_SiteList", Model)
    </div>

    <div class="container col-md-12">
        <div class="row pull-right">
            <a href="@Url.Action("ExportData", "Site", new { fileName = "Sites" })" class="btn btn-primary btn-sm">
                <span class="glyphicon glyphicon-export"></span>Export
            </a>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $('#activeId').focus();
        $('#activeId').val('@objSearch.Active');
        $('#search').val('@objSearch.SearchText');

        function keypressHandler(e) {
            if (e.which == 13) {
                e.preventDefault(); //stops default action: submitting form
                $(this).blur();
                $('#btnSearch').focus().click();//give your submit an ID
            }
        }

        $(this).keypress(keypressHandler);

        //Will refresh the Sites based on Activen or InActive
        $('#activeId').change(function () {
            var activeId = $('#activeId').val();
            var search = $('#search').val();
            $.ajax({
                url: '@Url.Action("GetSiteByActiveOrInActive", "Site")',
                //Passes the content of an input up
                data: { id: activeId, search: search },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                async: false,
                success: function (data) {
                    $('#output').children().remove();
                    $('#output').html(data);
                }
            });
        });

        //Will refresh the Sites based on selection on Search click.
        $('#btnSearch').click(function () {
            $("#dlgmodal").dialog('open');
            $('#dlgmodal span').text('Loading ...');
            var activeId = $('#activeId').val();
            var search = $('#search').val();

            $.ajax({
                url: '@Url.Action("GetSiteBySearch", "Site")',
                //Passes the content of an input up
                data: { id: activeId, search: search },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                //async: false,
                success: function (data) {
                    $('#output').children().remove();
                    $('#output').append($(data));
                    $("#dlgmodal").closest('.ui-dialog-content').dialog("close");
                }
            });
        });

        //Sorting
        $(document).on("click", ".sortby", function (ev) {
            var activeId = $('#activeId').val();
            var search = $('#search').val();
            var sortby = $(this).attr('data-sortBy');
            $.ajax({
                url: '@Url.Action("GetSitesBySort", "Site")',
                //Passes the content of an input up
                data: { id: activeId, search: search, sortby: sortby },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                async: false,
                success: function (data) {
                    $('#output').children().remove();
                    $('#output').html(data);
                }
            });
        });

    });

</script>

SPFS/Views/Site/SiteDetails.cshtml
@model SPFS.Models.SiteListViewModel

@{
    ViewBag.Title = "SiteDetails";
    var text = Model.SPFS_Active ? "Active" : "In Active";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.SiteID)


    <h2>Site Details</h2>

    <div class="container">
        <section class="well form-horizontal form-widgets col-sm-12" style="margin:10px; width:95%;">
            <h4 class="ra-well-title">
               Location : @Model.Name
            </h4>
            <hr />
            <div class="form-horizontal form-widgets col-sm-12">
                <div class="form-group">
                    @Html.LabelFor(model => model.Gdis_org_entity_ID, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Gdis_org_entity_ID</h5>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Gdis_org_Parent_ID, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Gdis_org_Parent_ID</h5>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Name</h5>
                    </div>
                </div>

               <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Address</h5>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.City</h5>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.State</h5>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Country</h5>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Postal_Code, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-4">
                        <h5>@Model.Postal_Code</h5>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.SPFS_Active, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="input-group">
                        <div class="input-group-addon">
                            @Html.CheckBoxFor(model => model.SPFS_Active, new { @class = "saccCheckbox", id = "IsActive" })
                        </div>
                        @Html.Label(text, new { @class = "label label-success", id = "ActiveText" })
                    </div>
                    @Html.ValidationMessageFor(model => model.SPFS_Active)


                </div>
            </div>
        </section>
        <div class="row col-md-12">
            <div class="row pull-right">
                <a href="@Url.Action("Index")" class="btn btn-primary btn-sm">
                    <span class="glyphicon glyphicon-circle-arrow-left"></span>Back to List
                </a>
                <button type="submit" class="btn btn-primary btn-sm" id="btnSave">
                    <span class="glyphicon glyphicon-floppy-save"></span>
                    <span>Save</span>
                </button>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $("input#IsActive").change(function () {
            var text = $(this).is(':checked') ? "Active" : "InActive"
            $("#ActiveText").html(text);
        });



    });

</script>

SPFS/Views/Site/_SiteList.cshtml
@using PagedList.Mvc;
@using PagedList;

@model IPagedList<SPFS.Models.SiteListViewModel>
@{

}
<div class="container col-md-12">
    <table class="table table-condensed table-hover">
        <tr class="active">
            <th>
                <a href="#" data-sortby="@ViewData["NameSort"]" class="sortby">@Html.DisplayNameFor(model => model.First().Name)</a>
            </th>
            <th>
                <a href="#" data-sortby="@ViewData["GDISORGSort"]" class="sortby">@Html.DisplayNameFor(model => model.First().Gdis_org_entity_ID)</a>
            </th>
            <th>
                <a href="#" data-sortby="@ViewData["GDISPARSort"]" class="sortby"> @Html.DisplayNameFor(model => model.First().Gdis_org_Parent_ID)</a>
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.First().Address)
            </th>*@
            <th>
                <a href="#" data-sortby="@ViewData["CountrySort"]" class="sortby">@Html.DisplayNameFor(model => model.First().Country)</a>
            </th>

            <th>
                <a href="#" data-sortby="@ViewData["ZipSort"]" class="sortby">@Html.DisplayNameFor(model => model.First().Postal_Code)</a>
            </th>
            <th class="actalign">
                <a href="#" data-sortby="@ViewData["IsActiveSort"]" class="sortby">@Html.DisplayNameFor(model => model.First().SPFS_Active)</a>
            </th>



        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="6">
                    <div class="alert alert-warning" role="alert">
                         <strong>Warning!</strong> @SPFS.Helpers.Utilities.NO_RESULT
                    </div>
                    @*<div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <strong>Warning!</strong> @SPFS.Helpers.Utilities.NO_RESULT
                    </div>*@
                </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {  @Html.HiddenFor(modelItem => item.SiteID)
                <tr>
                    <td>
                        @Html.ActionLink(item.Name,"SiteDetails",new { SiteID = item.SiteID })

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gdis_org_entity_ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gdis_org_Parent_ID)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.Country)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Postal_Code)

                       
                    </td>
                    <td style="text-align:center">
                          @Html.DisplayFor(modelItem =>item.SPFS_Active)                     
                    </td>


                </tr>
            }
        }
    </table>
    <div id="myPager">
        @if (Model.Count() > 0)
        {
            @Html.PagedListPager(Model, page => Url.Action("SearchByPage", new { page, search = Request.QueryString["search"], sortby = @ViewData["ActiveSort"], activeId = Convert.ToInt32(ViewData["ActiveId"]) }))
        }
    </div>
</div>