SPFS/Models/UserSites.cs
using SPFS.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SPFS.Models
{
    public class UserSites
    {

        public int UserSitesID { get; set; }
        public int UserID { get; set; }
        public int SiteID { get; set; }
        public System.DateTime Created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public string Modified_by { get; set; }

        public virtual SPFS_SITES SPFS_SITES { get; set; }
        public virtual SPFS_USERS SPFS_USERS { get; set; }
    }
    public class UserSitesViewModel
    {

        public string UserName { get; set; }
       
        [Required(ErrorMessage = "Please select User")]
        public int? UserID { get; set; }
       public List<int> SelectedSiteIDs { get; set; }

        public System.DateTime Created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public string Modified_by { get; set; }
    }
    public class SiteUsersViewModel
    {

        public string SiteName { get; set; }

        [Required(ErrorMessage = "Please select Location")]
        public int? SiteID { get; set; }
        public List<int> SelectedUserIDs { get; set; }

        public System.DateTime Created_date { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Modified_date { get; set; }
        public string Modified_by { get; set; }
    }
}

SPFS/Controllers/UserSitesController.cs
using SPFS.DAL;
using SPFS.Helpers;
using SPFS.Model;
using SPFS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SPFS.Controllers
{
    public class UserSitesController : BaseController
    {
        // GET: UserSites
        public ActionResult Index(int? userId)
        {
            CreateListViewBags();
            var viewModel = GetSitesModel(userId);
            return View(viewModel);
        }

        private UserSitesViewModel GetSitesModel(int? userId)
        {
            var viewModel = new UserSitesViewModel();
            viewModel.UserID = userId;
            var siteIds = new List<int>();
            using (Repository SteRep = new Repository())
            {
                siteIds = (from sit in SteRep.Context.SPFS_USERSITES
                           where sit.UserID == userId 
                           select sit.SiteID).ToList();
            }
            viewModel.SelectedSiteIDs = siteIds;
            return viewModel;
        }

        private void CreateListViewBags()
        {
            List<SelectListItem> sites;
            List<SelectListItem> users;
            using (Repository UserRep = new Repository())
            {
                sites = (from ste in UserRep.Context.SPFS_SITES
                         where ste.SPFS_Active == true
                         select new SelectListItem { Value = ste.SiteID.ToString(), Text = ste.Name }).ToList();
                users = (from usr in UserRep.Context.SPFS_USERS
                         where usr.SPFS_Active == true
                         select new SelectListItem { Value = usr.UserID.ToString(), Text = usr.UserName }).ToList();
            }
            ViewBag.Users = users;
            ViewBag.Sites = sites;
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult GetSitesForUser(int? userId)
        {
            try
            {
                
                CreateListViewBags();
                var viewModel = GetSitesModel(userId);
                return PartialView("_UserSitesList", viewModel);
            }
            catch
            {
                Utilities util = new Utilities();
                string msg = "error occured while loading sites information";
                throw new Exception(util.GetDivElements(msg, "alert alert-danger", "Error ! "));
            }
        }
        [HttpPost]
        public ActionResult Index(UserSitesViewModel viewModel)
        {

            if (ModelState.IsValid)
            {

                using (Repository UserRep = new Repository())
                {
                    Utilities utils = new Utilities();
                    var usersiteIds = (from usr in UserRep.Context.SPFS_USERSITES
                                       where usr.UserID == viewModel.UserID
                                       select usr.SiteID).ToList();

                    var deleteIds = (from id in usersiteIds
                                     where viewModel.SelectedSiteIDs == null ? true
                                     : !viewModel.SelectedSiteIDs.Contains(id)
                                     select id).ToList();
                    if (viewModel.SelectedSiteIDs != null)
                    {

                        foreach (var siteId in viewModel.SelectedSiteIDs)
                        {
                            if (usersiteIds.Contains(siteId))
                            {
                                var userSite = UserRep.Context.SPFS_USERSITES.FirstOrDefault(usrSite => usrSite.UserID == viewModel.UserID && usrSite.SiteID == siteId);
                                userSite.Modified_by = utils.GetCurrentUser().UserName;
                                userSite.Modified_date = DateTime.Now;
                            }
                            else
                            {
                                var userSite = new SPFS_USERSITES()
                                {
                                    UserID = viewModel.UserID.Value,
                                    SiteID = siteId,
                                    Created_by = utils.GetCurrentUser().UserName,
                                    Created_date = DateTime.Now,
                                };
                                UserRep.Context.SPFS_USERSITES.Add(userSite);
                            }
                        }
                    }
                    if (deleteIds != null && deleteIds.Count > 0)
                    {
                        var deleteList = UserRep.Context.SPFS_USERSITES.Where(ite => deleteIds.Contains(ite.SiteID) && ite.UserID == viewModel.UserID).AsEnumerable();
                        UserRep.Context.SPFS_USERSITES.RemoveRange(deleteList);
                    }
                    UserRep.Context.SaveChanges();

                    return RedirectToAction("Index", new { userId = viewModel.UserID });
                }
            }
            CreateListViewBags();
            return View(viewModel);
        }

        // GET: UserSites
        public ActionResult SitesUser(int? siteId)
        {
            CreateListViewBags();
            var viewmodel = GetUsersModel(siteId);
            return View(viewmodel);
        }

        private SiteUsersViewModel GetUsersModel(int? siteId)
        {
            var viewmodel = new SiteUsersViewModel();
            viewmodel.SiteID = siteId;
            var userIds = new List<int>();
            using (Repository UsrRep = new Repository())
            {
                userIds = (from usr in UsrRep.Context.SPFS_USERSITES
                           where usr.SiteID == siteId
                           select usr.UserID).ToList();
            }
            viewmodel.SelectedUserIDs = userIds;
            return viewmodel;
        }



        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult GetUsersForSite(int? siteId)
        {
            try
            {
                CreateListViewBags();
                var viewmodel = GetUsersModel(siteId);
                return PartialView("_SiteUsersList", viewmodel);
            }
            catch (Exception)
            {
                Utilities util = new Utilities();
                string msg = "error occured while loading users information";
                throw new Exception(util.GetDivElements(msg, "alert alert-danger", "Error ! "));

            }



        }
        [HttpPost]
        public ActionResult SitesUser(SiteUsersViewModel viewmodel)
        {

            if (ModelState.IsValid)
            {

                using (Repository SiteRep = new Repository())
                {
                    Utilities utils = new Utilities();
                    var siteuserIds = (from usr in SiteRep.Context.SPFS_USERSITES
                                       where usr.SiteID == viewmodel.SiteID
                                       select usr.UserID).ToList();

                    var deleteUsrIds = (from id in siteuserIds
                                        where viewmodel.SelectedUserIDs == null ? true
                                     : !viewmodel.SelectedUserIDs.Contains(id)
                                        select id).ToList();
                    if (viewmodel.SelectedUserIDs != null)
                    {

                        foreach (var userId in viewmodel.SelectedUserIDs)
                        {
                            if (siteuserIds.Contains(userId))
                            {
                                var siteUser = SiteRep.Context.SPFS_USERSITES.FirstOrDefault(usrSite => usrSite.SiteID == viewmodel.SiteID && usrSite.UserID == userId);
                                siteUser.Modified_by = utils.GetCurrentUser().UserName;
                                siteUser.Modified_date = DateTime.Now;
                            }
                            else
                            {
                                var siteUser = new SPFS_USERSITES()
                                {
                                    SiteID = viewmodel.SiteID.Value,
                                    UserID = userId,
                                    Created_by = utils.GetCurrentUser().UserName,
                                    Created_date = DateTime.Now,
                                };
                                SiteRep.Context.SPFS_USERSITES.Add(siteUser);
                            }
                        }
                    }
                    if (deleteUsrIds != null && deleteUsrIds.Count > 0)
                    {
                        var deleteList = SiteRep.Context.SPFS_USERSITES.Where(ite => deleteUsrIds.Contains(ite.UserID) && ite.UserID == viewmodel.SiteID).AsEnumerable();
                        SiteRep.Context.SPFS_USERSITES.RemoveRange(deleteList);
                    }
                    SiteRep.Context.SaveChanges();

                    return RedirectToAction("SitesUser", new { userId = viewmodel.SiteID });
                }
            }
            CreateListViewBags();
            return View(viewmodel);
        }
    }
}

SPFS/Views/UserSites/Index.cshtml
@model SPFS.Models.UserSitesViewModel

@{
    ViewBag.Title = "Index";

}

<h2>Add Sites to Users</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="row col-md-12" style="padding-top: 5px">

        <div class="col-md-12">
            <div class="form-group">
                @Html.Label("Select User :")
                @Html.DropDownListFor(model => model.UserID, ViewBag.Users as IEnumerable<SelectListItem>, "",
               new { @class = "selectpicker", data_live_search = "true", data_size = "10", data_width = "30%", required = "true" })

                @Html.ValidationMessageFor(model => model.UserID)

            </div>
        </div>
    </div>

    <div id="divsiteslist" class="row" style="margin-top: 5px; padding-left:25px">
        @Html.Partial("_UserSitesList", Model)

    </div>

    <div id="divsitesSave" class="row col-md-12" style="padding-left: 25px;">
        <span class="input-group-btn">
            <button id="btnSave" type="submit" value="Save" onclick="OnBeginPostBack_Save(this)" class="btn btn-primary btn-block" style="border-radius:5px">
                <span class="glyphicon glyphicon-floppy-save"></span>
                <span>Save</span>
            </button>
        </span>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        //var userId = $('#UserID').val();


        var userId = $("#UserID option:selected").val();
        if (userId == "") {
            $("#btnSave").hide();
            $("#divsiteslist").children().remove();
        }


        function loadSites(userId) {

            $("#dlgmodal").dialog('open');
            $('#dlgmodal span').text('Loading ...');
            var url = '@Url.Action("GetSitesForUser", "UserSites")';
            $.ajax({
                type: "GET",
                url: url,
                data: { userId: userId },
                success: function (data) {
                    $("#divsiteslist").html(data);
                },
                complete:
                  function (jqXHR, textStatus) {
                      $("#dlgmodal").closest('.ui-dialog-content').dialog("close");
                  },
                error: function (data) {

                }
            });
        }
        //Will refresh
     
        $('#UserID').change(function () {
            var userId = $("#UserID option:selected").val();
            if (userId != "") {

                $(this).valid();
                loadSites(userId);
                $("#btnSave").show();
            }

        });


    });

</script>

SPFS/Views/UserSites/SitesUser.cshtml
@model SPFS.Models.SiteUsersViewModel

@{
    ViewBag.Title = "SitesUser";
   
}

<h2>Add User to Sites</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="row col-md-12" style="padding-top: 5px">

        <div class="col-md-12">
            <div class="form-group">
                @Html.Label("Select Site :")
                @Html.DropDownListFor(model => model.SiteID, ViewBag.Sites as IEnumerable<SelectListItem>, "",
               new { @class = "selectpicker", data_live_search = "true", data_size = "10", data_width = "30%", required = "true" })

                @Html.ValidationMessageFor(model => model.SiteID)

            </div>
        </div>
    </div>

    <div id="divuserslist" class="row" style="margin-top: 5px; padding-left:25px">
        @Html.Partial("_SiteUsersList", Model)

    </div>
    <div id="divsitesSave" class="row col-md-12" style="padding-left: 25px;">
        <span class="input-group-btn">
            <button id="btnSave" type="submit" value="Save" onclick="OnBeginPostBack_Save(this)" class="btn btn-primary btn-block" style="border-radius:5px">
                <span class="glyphicon glyphicon-floppy-save"></span>
                <span>Save</span>
            </button>
        </span>


    </div>

}

<script type="text/javascript">
    $(document).ready(function () {
        //var userId = $('#UserID').val();


        var siteId = $("#SiteID option:selected").val();
        if (siteId == "") {
            $("#btnSave").hide();
            $("#divuserslist").children().remove();
        }


        function loadUsers(siteId) {
            $("#dlgmodal").dialog('open');
            $('#dlgmodal span').text('Loading ...');
            var url = '@Url.Action("GetUsersForSite", "UserSites")';
            $.ajax({
                type: "GET",
                url: url,
                data: { siteId: siteId },
                success: function (data) {
                    $("#divuserslist").html(data);
                },
                complete:
                  function (jqXHR, textStatus) {
                      $("#dlgmodal").closest('.ui-dialog-content').dialog("close");
                  },
                error: function (data) {
                    alert("error ");
                }
            });
        }
        //Will refresh
        //$('#UserID').change(function () {
        //    var userId = $('#UserID').val();
        //    if (userId != "") {

        //        loadSites(userId);
        //    }

        //});
        $('#SiteID').change(function () {
            var siteId = $("#SiteID option:selected").val();
            if (siteId != "") {

                $(this).valid();

                loadUsers(siteId);

                $("#btnSave").show();
            }

        });


    });

</script>

SPFS/Views/UserSites/_SiteUsersList.cshtml
@model SPFS.Models.SiteUsersViewModel

@*<div class="row col-md-12">
    <div class="col-md-12 divpnlStyle">
        <h4><br /></h4>
    </div>
</div>*@

<div class="row col-md-12">
    <div class="col-md-12" style="padding-bottom: 25px;">
        @Html.ListBoxFor(model => model.SelectedUserIDs, ViewBag.Users as IEnumerable<SelectListItem>, new { @class = "form-control", id = "SelectedUserIDs", @multiple = "multiple" })
    </div>
</div>
<br />

<script type="text/javascript">
    $(function () {
        $("#SelectedUserIDs").bootstrapDualListbox({
            nonSelectedListLabel: 'Available User(s)',
            selectedListLabel: 'Selected User(s)',
            preserveSelectionOnMove: 'moved',
            moveOnSelect: false,
            selectorMinimalHeight: 200
        });
    });
</script>

SPFS/Views/UserSites/_UserSitesList.cshtml
@model SPFS.Models.UserSitesViewModel


<div class="row col-md-12">
    <div class="col-md-12 divpnlStyle">
        <h4><br /></h4>
    </div>
</div>

<div class="row col-md-12">
    <div class="col-md-12" style="padding-bottom: 25px;">
        @Html.ListBoxFor(model => model.SelectedSiteIDs, ViewBag.Sites as IEnumerable<SelectListItem>, new { @class = "form-control", id = "SelectedSiteIDs", @multiple = "multiple" })
    </div>
</div>
<br/>

<script type="text/javascript">
    $(function () {
        $("#SelectedSiteIDs").bootstrapDualListbox({
            nonSelectedListLabel: 'Available Site(s)',
            selectedListLabel: 'Selected Site(s)',
            preserveSelectionOnMove: 'moved',
            moveOnSelect: false,
            selectorMinimalHeight: 200
        });
    });
</script>